FROM {{ base_image }}
{% if maintainer -%}
MAINTAINER {{ maintainer }}
{% endif %}

{% for k,v in envvars.iteritems() -%}
ENV {{ k }} {{ v }}
{% endfor -%}

RUN {% for command in commands[:-1] -%}{{ command|safe }} && {% endfor -%} {{ commands[-1]|safe }}
